// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package main

import (
	"github.com/tinylib/msgp/msgp"
)

// MarshalMsg implements msgp.Marshaler
func (z *cachedDebugArtifacts) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "SourceFiles"
	o = append(o, 0x82, 0xab, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.SourceFiles)))
	for za0001, za0002 := range z.SourceFiles {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendBytes(o, za0002)
	}
	// string "GarbledFiles"
	o = append(o, 0xac, 0x47, 0x61, 0x72, 0x62, 0x6c, 0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.GarbledFiles)))
	for za0003, za0004 := range z.GarbledFiles {
		o = msgp.AppendString(o, za0003)
		o = msgp.AppendBytes(o, za0004)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *cachedDebugArtifacts) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "SourceFiles":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceFiles")
				return
			}
			if z.SourceFiles == nil {
				z.SourceFiles = make(map[string][]byte, zb0002)
			} else if len(z.SourceFiles) > 0 {
				clear(z.SourceFiles)
			}
			for zb0002 > 0 {
				var za0002 []byte
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "SourceFiles")
					return
				}
				za0002, bts, err = msgp.ReadBytesBytes(bts, za0002)
				if err != nil {
					err = msgp.WrapError(err, "SourceFiles", za0001)
					return
				}
				z.SourceFiles[za0001] = za0002
			}
		case "GarbledFiles":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "GarbledFiles")
				return
			}
			if z.GarbledFiles == nil {
				z.GarbledFiles = make(map[string][]byte, zb0003)
			} else if len(z.GarbledFiles) > 0 {
				clear(z.GarbledFiles)
			}
			for zb0003 > 0 {
				var za0004 []byte
				zb0003--
				var za0003 string
				za0003, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "GarbledFiles")
					return
				}
				za0004, bts, err = msgp.ReadBytesBytes(bts, za0004)
				if err != nil {
					err = msgp.WrapError(err, "GarbledFiles", za0003)
					return
				}
				z.GarbledFiles[za0003] = za0004
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *cachedDebugArtifacts) Msgsize() (s int) {
	s = 1 + 12 + msgp.MapHeaderSize
	if z.SourceFiles != nil {
		for za0001, za0002 := range z.SourceFiles {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.BytesPrefixSize + len(za0002)
		}
	}
	s += 13 + msgp.MapHeaderSize
	if z.GarbledFiles != nil {
		for za0003, za0004 := range z.GarbledFiles {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.BytesPrefixSize + len(za0004)
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z goAsmNames) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	o = msgp.AppendMapHeader(o, uint32(len(z)))
	for za0001, za0002 := range z {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *goAsmNames) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var zb0003 uint32
	zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(goAsmNames, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		var zb0002 string
		zb0003--
		var zb0001 string
		zb0001, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		zb0002, bts, err = msgp.ReadStringBytes(bts)
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z goAsmNames) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0004, zb0005 := range z {
			_ = zb0005
			s += msgp.StringPrefixSize + len(zb0004) + msgp.StringPrefixSize + len(zb0005)
		}
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *pkgCache) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 2
	// string "ReflectAPIs"
	o = append(o, 0x82, 0xab, 0x52, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x41, 0x50, 0x49, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.ReflectAPIs)))
	for za0001, za0002 := range z.ReflectAPIs {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendMapHeader(o, uint32(len(za0002)))
		for za0003, za0004 := range za0002 {
			o = msgp.AppendInt(o, za0003)
			o = msgp.AppendBool(o, za0004)
		}
	}
	// string "ReflectObjectNames"
	o = append(o, 0xb2, 0x52, 0x65, 0x66, 0x6c, 0x65, 0x63, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.ReflectObjectNames)))
	for za0005, za0006 := range z.ReflectObjectNames {
		o = msgp.AppendString(o, za0005)
		o = msgp.AppendString(o, za0006)
	}
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *pkgCache) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "ReflectAPIs":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReflectAPIs")
				return
			}
			if z.ReflectAPIs == nil {
				z.ReflectAPIs = make(map[string]map[int]bool, zb0002)
			} else if len(z.ReflectAPIs) > 0 {
				clear(z.ReflectAPIs)
			}
			for zb0002 > 0 {
				var za0002 map[int]bool
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ReflectAPIs")
					return
				}
				var zb0003 uint32
				zb0003, bts, err = msgp.ReadMapHeaderBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ReflectAPIs", za0001)
					return
				}
				if za0002 == nil {
					za0002 = make(map[int]bool, zb0003)
				} else if len(za0002) > 0 {
					clear(za0002)
				}
				for zb0003 > 0 {
					var za0004 bool
					zb0003--
					var za0003 int
					za0003, bts, err = msgp.ReadIntBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "ReflectAPIs", za0001, za0003)
						return
					}
					za0004, bts, err = msgp.ReadBoolBytes(bts)
					if err != nil {
						err = msgp.WrapError(err, "ReflectAPIs", za0001, za0003)
						return
					}
					za0002[za0003] = za0004
				}
				z.ReflectAPIs[za0001] = za0002
			}
		case "ReflectObjectNames":
			var zb0004 uint32
			zb0004, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "ReflectObjectNames")
				return
			}
			if z.ReflectObjectNames == nil {
				z.ReflectObjectNames = make(map[string]string, zb0004)
			} else if len(z.ReflectObjectNames) > 0 {
				clear(z.ReflectObjectNames)
			}
			for zb0004 > 0 {
				var za0006 string
				zb0004--
				var za0005 string
				za0005, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ReflectObjectNames")
					return
				}
				za0006, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "ReflectObjectNames", za0005)
					return
				}
				z.ReflectObjectNames[za0005] = za0006
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *pkgCache) Msgsize() (s int) {
	s = 1 + 12 + msgp.MapHeaderSize
	if z.ReflectAPIs != nil {
		for za0001, za0002 := range z.ReflectAPIs {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.MapHeaderSize
			if za0002 != nil {
				for za0003, za0004 := range za0002 {
					_ = za0004
					_ = za0003
					s += msgp.IntSize + msgp.BoolSize
				}
			}
		}
	}
	s += 19 + msgp.MapHeaderSize
	if z.ReflectObjectNames != nil {
		for za0005, za0006 := range z.ReflectObjectNames {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005) + msgp.StringPrefixSize + len(za0006)
		}
	}
	return
}
