// Code generated by scripts/gen_go_std_tables.go; DO NOT EDIT.

// Generated from Go versions [go1.23.3].

package main

var runtimeAndDeps = map[string]bool{
	"internal/abi":              true, // go1.23
	"internal/bytealg":          true, // go1.23
	"internal/byteorder":        true, // go1.23
	"internal/chacha8rand":      true, // go1.23
	"internal/coverage/rtcov":   true, // go1.23
	"internal/cpu":              true, // go1.23
	"internal/goarch":           true, // go1.23
	"internal/godebugs":         true, // go1.23
	"internal/goexperiment":     true, // go1.23
	"internal/goos":             true, // go1.23
	"internal/profilerecord":    true, // go1.23
	"internal/runtime/atomic":   true, // go1.23
	"internal/runtime/exithook": true, // go1.23
	"internal/runtime/syscall":  true, // go1.23
	"internal/stringslite":      true, // go1.23
	"runtime":                   true, // go1.23
	"runtime/internal/math":     true, // go1.23
	"runtime/internal/sys":      true, // go1.23
	"unsafe":                    true, // go1.23
}

var runtimeLinknamed = []string{
	"arena",                          // go1.23
	"crypto/internal/boring",         // go1.23
	"crypto/internal/boring/bcache",  // go1.23
	"crypto/internal/boring/fipstls", // go1.23
	"crypto/x509/internal/macos",     // go1.23
	"internal/coverage/cfile",        // go1.23
	"internal/godebug",               // go1.23
	"internal/poll",                  // go1.23
	"internal/reflectlite",           // go1.23
	"internal/syscall/unix",          // go1.23
	"internal/syscall/windows",       // go1.23
	"internal/weak",                  // go1.23
	"maps",                           // go1.23
	"os",                             // go1.23
	"os/signal",                      // go1.23
	"plugin",                         // go1.23
	"reflect",                        // go1.23
	"runtime/debug",                  // go1.23
	"runtime/metrics",                // go1.23
	"runtime/pprof",                  // go1.23
	"runtime/trace",                  // go1.23
	"sync",                           // go1.23
	"sync/atomic",                    // go1.23
	"syscall",                        // go1.23
	"syscall/js",                     // go1.23
	"time",                           // go1.23
	"unique",                         // go1.23
	// The net package linknames to the runtime, not the other way around.
	// TODO: support this automatically via our script.
	"net",
}

var compilerIntrinsics = map[string]map[string]bool{
	"internal/runtime/atomic": {
		"And":             true, // go1.23
		"And32":           true, // go1.23
		"And64":           true, // go1.23
		"And8":            true, // go1.23
		"Anduintptr":      true, // go1.23
		"Cas":             true, // go1.23
		"Cas64":           true, // go1.23
		"CasRel":          true, // go1.23
		"Casint32":        true, // go1.23
		"Casint64":        true, // go1.23
		"Casp1":           true, // go1.23
		"Casuintptr":      true, // go1.23
		"Load":            true, // go1.23
		"Load64":          true, // go1.23
		"Load8":           true, // go1.23
		"LoadAcq":         true, // go1.23
		"LoadAcq64":       true, // go1.23
		"LoadAcquintptr":  true, // go1.23
		"Loadint32":       true, // go1.23
		"Loadint64":       true, // go1.23
		"Loadp":           true, // go1.23
		"Loaduint":        true, // go1.23
		"Loaduintptr":     true, // go1.23
		"Or":              true, // go1.23
		"Or32":            true, // go1.23
		"Or64":            true, // go1.23
		"Or8":             true, // go1.23
		"Oruintptr":       true, // go1.23
		"Store":           true, // go1.23
		"Store64":         true, // go1.23
		"Store8":          true, // go1.23
		"StoreRel":        true, // go1.23
		"StoreRel64":      true, // go1.23
		"StoreReluintptr": true, // go1.23
		"Storeint32":      true, // go1.23
		"Storeint64":      true, // go1.23
		"StorepNoWB":      true, // go1.23
		"Storeuintptr":    true, // go1.23
		"Xadd":            true, // go1.23
		"Xadd64":          true, // go1.23
		"Xaddint32":       true, // go1.23
		"Xaddint64":       true, // go1.23
		"Xadduintptr":     true, // go1.23
		"Xchg":            true, // go1.23
		"Xchg64":          true, // go1.23
		"Xchgint32":       true, // go1.23
		"Xchgint64":       true, // go1.23
		"Xchguintptr":     true, // go1.23
	},
	"math": {
		"Abs":         true, // go1.23
		"Ceil":        true, // go1.23
		"Copysign":    true, // go1.23
		"FMA":         true, // go1.23
		"Floor":       true, // go1.23
		"Round":       true, // go1.23
		"RoundToEven": true, // go1.23
		"Trunc":       true, // go1.23
		"sqrt":        true, // go1.23
	},
	"math/big": {
		"mulWW": true, // go1.23
	},
	"math/bits": {
		"Add":             true, // go1.23
		"Add64":           true, // go1.23
		"Div":             true, // go1.23
		"Div64":           true, // go1.23
		"Len":             true, // go1.23
		"Len16":           true, // go1.23
		"Len32":           true, // go1.23
		"Len64":           true, // go1.23
		"Len8":            true, // go1.23
		"Mul":             true, // go1.23
		"Mul64":           true, // go1.23
		"OnesCount":       true, // go1.23
		"OnesCount16":     true, // go1.23
		"OnesCount32":     true, // go1.23
		"OnesCount64":     true, // go1.23
		"OnesCount8":      true, // go1.23
		"Reverse":         true, // go1.23
		"Reverse16":       true, // go1.23
		"Reverse32":       true, // go1.23
		"Reverse64":       true, // go1.23
		"Reverse8":        true, // go1.23
		"ReverseBytes16":  true, // go1.23
		"ReverseBytes32":  true, // go1.23
		"ReverseBytes64":  true, // go1.23
		"RotateLeft":      true, // go1.23
		"RotateLeft16":    true, // go1.23
		"RotateLeft32":    true, // go1.23
		"RotateLeft64":    true, // go1.23
		"RotateLeft8":     true, // go1.23
		"Sub":             true, // go1.23
		"Sub64":           true, // go1.23
		"TrailingZeros16": true, // go1.23
		"TrailingZeros32": true, // go1.23
		"TrailingZeros64": true, // go1.23
		"TrailingZeros8":  true, // go1.23
	},
	"runtime": {
		"publicationBarrier": true, // go1.23
	},
	"runtime/internal/math": {
		"MulUintptr": true, // go1.23
	},
	"runtime/internal/sys": {
		"Bswap32":          true, // go1.23
		"Bswap64":          true, // go1.23
		"Len64":            true, // go1.23
		"Len8":             true, // go1.23
		"OnesCount64":      true, // go1.23
		"Prefetch":         true, // go1.23
		"PrefetchStreamed": true, // go1.23
		"TrailingZeros32":  true, // go1.23
		"TrailingZeros64":  true, // go1.23
		"TrailingZeros8":   true, // go1.23
	},
	"sync": {
		"runtime_LoadAcquintptr":  true, // go1.23
		"runtime_StoreReluintptr": true, // go1.23
	},
	"sync/atomic": {
		"AddInt32":              true, // go1.23
		"AddInt64":              true, // go1.23
		"AddUint32":             true, // go1.23
		"AddUint64":             true, // go1.23
		"AddUintptr":            true, // go1.23
		"AndInt32":              true, // go1.23
		"AndInt64":              true, // go1.23
		"AndUint32":             true, // go1.23
		"AndUint64":             true, // go1.23
		"AndUintptr":            true, // go1.23
		"CompareAndSwapInt32":   true, // go1.23
		"CompareAndSwapInt64":   true, // go1.23
		"CompareAndSwapUint32":  true, // go1.23
		"CompareAndSwapUint64":  true, // go1.23
		"CompareAndSwapUintptr": true, // go1.23
		"LoadInt32":             true, // go1.23
		"LoadInt64":             true, // go1.23
		"LoadPointer":           true, // go1.23
		"LoadUint32":            true, // go1.23
		"LoadUint64":            true, // go1.23
		"LoadUintptr":           true, // go1.23
		"OrInt32":               true, // go1.23
		"OrInt64":               true, // go1.23
		"OrUint32":              true, // go1.23
		"OrUint64":              true, // go1.23
		"OrUintptr":             true, // go1.23
		"StoreInt32":            true, // go1.23
		"StoreInt64":            true, // go1.23
		"StoreUint32":           true, // go1.23
		"StoreUint64":           true, // go1.23
		"StoreUintptr":          true, // go1.23
		"SwapInt32":             true, // go1.23
		"SwapInt64":             true, // go1.23
		"SwapUint32":            true, // go1.23
		"SwapUint64":            true, // go1.23
		"SwapUintptr":           true, // go1.23
	},
}

var reflectSkipPkg = map[string]bool{
	"fmt": true,
}
