// Code generated by scripts/gen_go_std_tables.go; DO NOT EDIT.

// Generated from Go versions [go1.27.0].

package main

// runtimeAndDeps contains the runtime package and all of its transitive dependencies
// as reported by 'go list -deps'.
var runtimeAndDeps = map[string]bool{
	"internal/abi":                     true, // go1.27 linux/amd64
	"internal/asan":                    true, // go1.27 linux/amd64
	"internal/bytealg":                 true, // go1.27 linux/amd64
	"internal/byteorder":               true, // go1.27 linux/amd64
	"internal/chacha8rand":             true, // go1.27 linux/amd64
	"internal/coverage/rtcov":          true, // go1.27 linux/amd64
	"internal/cpu":                     true, // go1.27 linux/amd64
	"internal/goarch":                  true, // go1.27 linux/amd64
	"internal/godebugs":                true, // go1.27 linux/amd64
	"internal/goexperiment":            true, // go1.27 linux/amd64
	"internal/goos":                    true, // go1.27 linux/amd64
	"internal/msan":                    true, // go1.27 linux/amd64
	"internal/profilerecord":           true, // go1.27 linux/amd64
	"internal/race":                    true, // go1.27 linux/amd64
	"internal/runtime/atomic":          true, // go1.27 linux/amd64
	"internal/runtime/cgroup":          true, // go1.27 linux/amd64
	"internal/runtime/exithook":        true, // go1.27 linux/amd64
	"internal/runtime/gc":              true, // go1.27 linux/amd64
	"internal/runtime/gc/scan":         true, // go1.27 linux/amd64
	"internal/runtime/maps":            true, // go1.27 linux/amd64
	"internal/runtime/math":            true, // go1.27 linux/amd64
	"internal/runtime/pprof/label":     true, // go1.27 linux/amd64
	"internal/runtime/sys":             true, // go1.27 linux/amd64
	"internal/runtime/syscall/linux":   true, // go1.27 linux/amd64
	"internal/runtime/syscall/windows": true, // go1.27 windows/386
	"internal/strconv":                 true, // go1.27 linux/amd64
	"internal/stringslite":             true, // go1.27 linux/amd64
	"internal/trace/tracev2":           true, // go1.27 linux/amd64
	"math/bits":                        true, // go1.27 linux/amd64
	"runtime":                          true, // go1.27 linux/amd64
	"structs":                          true, // go1.27 wasip1/wasm
	"unsafe":                           true, // go1.27 linux/amd64
}

// runtimeAndLinknamed contains the runtime package and all the packages
// which it points to via //go:linkname directives.
// We need to track these as some are not imported as transitive dependencies,
// and we need to load these to properly obfuscate the linkname target names.
//
// Note that runtimeAndLinknamed may contain duplicates with runtimeAndDeps.
// This is on purpose; some packages are in runtimeAndDeps via 'go list -deps'
// but not transitively imported on some platforms, even though they are used
// from the runtime package via //go:linkname directives on those platforms.
// To make sure we have coverage on all platforms, we allow duplicates.
var runtimeAndLinknamed = map[string]bool{
	"arena":                            true, // go1.27
	"crypto/fips140":                   true, // go1.27
	"crypto/internal/boring":           true, // go1.27
	"crypto/internal/boring/bcache":    true, // go1.27
	"crypto/internal/fips140":          true, // go1.27
	"crypto/internal/fips140deps/time": true, // go1.27
	"crypto/internal/sysrand":          true, // go1.27
	"crypto/rand":                      true, // go1.27
	"crypto/subtle":                    true, // go1.27
	"crypto/x509/internal/macos":       true, // go1.27
	"internal/bytealg":                 true, // go1.27
	"internal/coverage/cfile":          true, // go1.27
	"internal/cpu":                     true, // go1.27
	"internal/godebug":                 true, // go1.27
	"internal/poll":                    true, // go1.27
	"internal/race":                    true, // go1.27
	"internal/reflectlite":             true, // go1.27
	"internal/runtime/atomic":          true, // go1.27
	"internal/runtime/cgroup":          true, // go1.27
	"internal/runtime/maps":            true, // go1.27
	"internal/sync":                    true, // go1.27
	"internal/synctest":                true, // go1.27
	"internal/syscall/unix":            true, // go1.27
	"internal/syscall/windows":         true, // go1.27
	"maps":                             true, // go1.27
	"os":                               true, // go1.27
	"os/signal":                        true, // go1.27
	"plugin":                           true, // go1.27
	"reflect":                          true, // go1.27
	"runtime":                          true, // go1.27
	"runtime/debug":                    true, // go1.27
	"runtime/metrics":                  true, // go1.27
	"runtime/pprof":                    true, // go1.27
	"runtime/secret":                   true, // go1.27
	"runtime/trace":                    true, // go1.27
	"sync":                             true, // go1.27
	"sync/atomic":                      true, // go1.27
	"sync_test":                        true, // go1.27
	"syscall":                          true, // go1.27
	"syscall/js":                       true, // go1.27
	"time":                             true, // go1.27
	"unique":                           true, // go1.27
	"weak":                             true, // go1.27
	// The net package linknames to the runtime, not the other way around.
	"net": true,
	// The testing package uses a //go:linkname directive pointing to testing/synctest,
	// but it doesn't import the package, presumably to avoid an import cycle.
	"testing/synctest": true,
}

var compilerIntrinsics = map[string]map[string]bool{
	"crypto/internal/constanttime": {
		"Select":      true, // go1.27
		"boolToUint8": true, // go1.27
	},
	"internal/runtime/atomic": {
		"And":             true, // go1.27
		"And32":           true, // go1.27
		"And64":           true, // go1.27
		"And8":            true, // go1.27
		"Anduintptr":      true, // go1.27
		"Cas":             true, // go1.27
		"Cas64":           true, // go1.27
		"CasRel":          true, // go1.27
		"Casint32":        true, // go1.27
		"Casint64":        true, // go1.27
		"Casp1":           true, // go1.27
		"Casuintptr":      true, // go1.27
		"Load":            true, // go1.27
		"Load64":          true, // go1.27
		"Load8":           true, // go1.27
		"LoadAcq":         true, // go1.27
		"LoadAcq64":       true, // go1.27
		"LoadAcquintptr":  true, // go1.27
		"Loadint32":       true, // go1.27
		"Loadint64":       true, // go1.27
		"Loadp":           true, // go1.27
		"Loaduint":        true, // go1.27
		"Loaduintptr":     true, // go1.27
		"Or":              true, // go1.27
		"Or32":            true, // go1.27
		"Or64":            true, // go1.27
		"Or8":             true, // go1.27
		"Oruintptr":       true, // go1.27
		"Store":           true, // go1.27
		"Store64":         true, // go1.27
		"Store8":          true, // go1.27
		"StoreRel":        true, // go1.27
		"StoreRel64":      true, // go1.27
		"StoreReluintptr": true, // go1.27
		"Storeint32":      true, // go1.27
		"Storeint64":      true, // go1.27
		"StorepNoWB":      true, // go1.27
		"Storeuintptr":    true, // go1.27
		"Xadd":            true, // go1.27
		"Xadd64":          true, // go1.27
		"Xaddint32":       true, // go1.27
		"Xaddint64":       true, // go1.27
		"Xadduintptr":     true, // go1.27
		"Xchg":            true, // go1.27
		"Xchg64":          true, // go1.27
		"Xchg8":           true, // go1.27
		"Xchgint32":       true, // go1.27
		"Xchgint64":       true, // go1.27
		"Xchguintptr":     true, // go1.27
	},
	"internal/runtime/maps": {
		"bitsetFirst":                  true, // go1.27
		"bitsetLowestSet":              true, // go1.27
		"bitsetRemoveBelow":            true, // go1.27
		"bitsetShiftOutLowest":         true, // go1.27
		"ctrlGroupMatchEmpty":          true, // go1.27
		"ctrlGroupMatchEmptyOrDeleted": true, // go1.27
		"ctrlGroupMatchFull":           true, // go1.27
		"ctrlGroupMatchH2":             true, // go1.27
	},
	"internal/runtime/math": {
		"Add64":      true, // go1.27
		"MulUintptr": true, // go1.27
	},
	"internal/runtime/sys": {
		"Bswap32":          true, // go1.27
		"Bswap64":          true, // go1.27
		"GetCallerPC":      true, // go1.27
		"GetCallerSP":      true, // go1.27
		"GetClosurePtr":    true, // go1.27
		"Len64":            true, // go1.27
		"Len8":             true, // go1.27
		"OnesCount64":      true, // go1.27
		"Prefetch":         true, // go1.27
		"PrefetchStreamed": true, // go1.27
		"TrailingZeros32":  true, // go1.27
		"TrailingZeros64":  true, // go1.27
		"TrailingZeros8":   true, // go1.27
	},
	"math": {
		"Abs":         true, // go1.27
		"Ceil":        true, // go1.27
		"Copysign":    true, // go1.27
		"FMA":         true, // go1.27
		"Floor":       true, // go1.27
		"Round":       true, // go1.27
		"RoundToEven": true, // go1.27
		"Trunc":       true, // go1.27
		"sqrt":        true, // go1.27
	},
	"math/big": {
		"mulWW": true, // go1.27
	},
	"math/bits": {
		"Add":             true, // go1.27
		"Add64":           true, // go1.27
		"Div":             true, // go1.27
		"Div64":           true, // go1.27
		"Len":             true, // go1.27
		"Len16":           true, // go1.27
		"Len32":           true, // go1.27
		"Len64":           true, // go1.27
		"Len8":            true, // go1.27
		"Mul":             true, // go1.27
		"Mul64":           true, // go1.27
		"OnesCount":       true, // go1.27
		"OnesCount16":     true, // go1.27
		"OnesCount32":     true, // go1.27
		"OnesCount64":     true, // go1.27
		"OnesCount8":      true, // go1.27
		"Reverse":         true, // go1.27
		"Reverse16":       true, // go1.27
		"Reverse32":       true, // go1.27
		"Reverse64":       true, // go1.27
		"Reverse8":        true, // go1.27
		"ReverseBytes16":  true, // go1.27
		"ReverseBytes32":  true, // go1.27
		"ReverseBytes64":  true, // go1.27
		"RotateLeft":      true, // go1.27
		"RotateLeft16":    true, // go1.27
		"RotateLeft32":    true, // go1.27
		"RotateLeft64":    true, // go1.27
		"RotateLeft8":     true, // go1.27
		"Sub":             true, // go1.27
		"Sub64":           true, // go1.27
		"TrailingZeros16": true, // go1.27
		"TrailingZeros32": true, // go1.27
		"TrailingZeros64": true, // go1.27
		"TrailingZeros8":  true, // go1.27
	},
	"runtime": {
		"KeepAlive":            true, // go1.27
		"memequal":             true, // go1.27
		"publicationBarrier":   true, // go1.27
		"slicebytetostringtmp": true, // go1.27
	},
	"sync/atomic": {
		"AddInt32":              true, // go1.27
		"AddInt64":              true, // go1.27
		"AddUint32":             true, // go1.27
		"AddUint64":             true, // go1.27
		"AddUintptr":            true, // go1.27
		"AndInt32":              true, // go1.27
		"AndInt64":              true, // go1.27
		"AndUint32":             true, // go1.27
		"AndUint64":             true, // go1.27
		"AndUintptr":            true, // go1.27
		"CompareAndSwapInt32":   true, // go1.27
		"CompareAndSwapInt64":   true, // go1.27
		"CompareAndSwapUint32":  true, // go1.27
		"CompareAndSwapUint64":  true, // go1.27
		"CompareAndSwapUintptr": true, // go1.27
		"LoadInt32":             true, // go1.27
		"LoadInt64":             true, // go1.27
		"LoadPointer":           true, // go1.27
		"LoadUint32":            true, // go1.27
		"LoadUint64":            true, // go1.27
		"LoadUintptr":           true, // go1.27
		"OrInt32":               true, // go1.27
		"OrInt64":               true, // go1.27
		"OrUint32":              true, // go1.27
		"OrUint64":              true, // go1.27
		"OrUintptr":             true, // go1.27
		"StoreInt32":            true, // go1.27
		"StoreInt64":            true, // go1.27
		"StoreUint32":           true, // go1.27
		"StoreUint64":           true, // go1.27
		"StoreUintptr":          true, // go1.27
		"SwapInt32":             true, // go1.27
		"SwapInt64":             true, // go1.27
		"SwapUint32":            true, // go1.27
		"SwapUint64":            true, // go1.27
		"SwapUintptr":           true, // go1.27
	},
}

var reflectSkipPkg = map[string]bool{
	"fmt": true,
}
