// Copyright (c) 2024, The Garble Authors.
// See LICENSE for licensing information.

//go:build ignore

// This is a program used with `go generate`, so it handles errors via panic.
package main

import (
	"bytes"
	"cmp"
	"fmt"
	"go/format"
	"go/version"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"text/template"
)

type goPlatform struct {
	GOOS, GOARCH string
	Priority     int // smaller wins when deduplicating
}

func (p goPlatform) String() string {
	return fmt.Sprintf("%s/%s", p.GOOS, p.GOARCH)
}

// Cover the three main OSes, WASI, and a variety of x86/Arm and 64/32 bit
// platforms when calling `go list` commands to ensure we find all relevant
// packages.
var goPlatforms = []goPlatform{
	{"linux", "amd64", 1},
	{"darwin", "arm64", 2},
	{"windows", "386", 3},
	{"wasip1", "wasm", 4},
}
var goVersions = []string{"go1.27.0"}

var tmplTables = template.Must(template.New("").Parse(`
// Code generated by scripts/gen_go_std_tables.go; DO NOT EDIT.

// Generated from Go versions {{ .GoVersions }}.

package main

// runtimePkgPaths lists packages that cmd/internal/objabi marks as runtime
// packages, which the compiler handles specially for write barriers, nosplit,
// and related checks.
var runtimePkgPaths = []string{
{{- range $path := .RuntimePkgPaths }}
	"{{ $path.String }}", // {{ $path.GoVersionLang }}
{{- end }}
}

// runtimeAndLinknamed contains the runtime package and all the packages
// which it points to via //go:linkname directives.
// We need to track these as some are not imported as transitive dependencies,
// and we need to load these to properly obfuscate the linkname target names.
var runtimeAndLinknamed = map[string]bool{
{{- range $path := .RuntimeAndLinknamed }}
	"{{ $path.String }}": true, // {{ $path.GoVersionLang }}
{{- end }}
	// The net package linknames to the runtime, not the other way around.
	"net": true,
	// The testing package uses a //go:linkname directive pointing to testing/synctest,
	// but it doesn't import the package, presumably to avoid an import cycle.
	"testing/synctest": true,
}

var compilerIntrinsics = map[string]map[string]bool{
{{- range $intr := .CompilerIntrinsics }}
	"{{ $intr.Path }}": {
{{- range $name := $intr.Names }}
		"{{ $name.String }}": true, // {{ $name.GoVersionLang }}
{{- end }}
	},
{{- end }}
}

var builtinSymbols = map[string][]string{
	"internal/runtime/sys": {
		"nih",
	},
	"internal/runtime/atomic": {
		"align64",
	},
	"sync/atomic": {
		"align64",
	},
	"runtime": {
		// The compiler recognizes this named type to select hexadecimal
		// formatting for runtime print calls.
		"hex",
		"fmin32",
		"fmin64",
		"fmax32",
		"fmax64",
		"newobject",
		"mallocgc",
		"panicdivide",
		"panicshift",
		"panicmakeslicelen",
		"panicmakeslicecap",
		"throwinit",
		"panicwrap",
		"gopanic",
		"goexit",
		"gorecover",
		"goschedguarded",
		"goPanicIndex",
		"goPanicIndexU",
		"goPanicSliceAlen",
		"goPanicSliceAlenU",
		"goPanicSliceAcap",
		"goPanicSliceAcapU",
		"goPanicSliceB",
		"goPanicSliceBU",
		"goPanicSlice3Alen",
		"goPanicSlice3AlenU",
		"goPanicSlice3Acap",
		"goPanicSlice3AcapU",
		"goPanicSlice3B",
		"goPanicSlice3BU",
		"goPanicSlice3C",
		"goPanicSlice3CU",
		"goPanicSliceConvert",
		"printbool",
		"printfloat64",
		"printfloat32",
		"printint",
		"printhex",
		"printuint",
		"printcomplex128",
		"printcomplex64",
		"printstring",
		"printquoted",
		"printpointer",
		"printuintptr",
		"printiface",
		"printeface",
		"printslice",
		"printnl",
		"printsp",
		"printlock",
		"printunlock",
		"concatstring2",
		"concatstring3",
		"concatstring4",
		"concatstring5",
		"concatstrings",
		"concatbyte2",
		"concatbyte3",
		"concatbyte4",
		"concatbyte5",
		"concatbytes",
		"cmpstring",
		"intstring",
		"slicebytetostring",
		"slicebytetostringtmp",
		"slicerunetostring",
		"stringtoslicebyte",
		"stringtoslicerune",
		"slicecopy",
		"decoderune",
		"countrunes",
		"convT",
		"convTnoptr",
		"convT16",
		"convT32",
		"convT64",
		"convTstring",
		"convTslice",
		"assertE2I",
		"assertE2I2",
		"panicdottypeE",
		"panicdottypeI",
		"panicnildottype",
		"typeAssert",
		"interfaceSwitch",
		"ifaceeq",
		"efaceeq",
		"panicrangestate",
		"deferrangefunc",
		"rand",
		"rand32",
		"makemap64",
		"makemap",
		"makemap_small",
		"mapaccess1",
		"mapaccess1_fast32",
		"mapaccess1_fast64",
		"mapaccess1_faststr",
		"mapaccess1_fat",
		"mapaccess2",
		"mapaccess2_fast32",
		"mapaccess2_fast64",
		"mapaccess2_faststr",
		"mapaccess2_fat",
		"mapassign",
		"mapassign_fast32",
		"mapassign_fast32ptr",
		"mapassign_fast64",
		"mapassign_fast64ptr",
		"mapassign_faststr",
		"mapIterStart",
		"mapdelete",
		"mapdelete_fast32",
		"mapdelete_fast64",
		"mapdelete_faststr",
		"mapIterNext",
		"mapclear",
		"makechan64",
		"makechan",
		"chanrecv1",
		"chanrecv2",
		"chansend1",
		"closechan",
		"chanlen",
		"chancap",
		"writeBarrier",
		"typedmemmove",
		"typedmemclr",
		"typedslicecopy",
		"selectnbsend",
		"selectnbrecv",
		"selectsetpc",
		"selectgo",
		"block",
		"makeslice",
		"makeslice64",
		"makeslicecopy",
		"growslice",
		"growsliceBuf",
		"growsliceBufNoAlias",
		"growsliceNoAlias",
		"unsafeslicecheckptr",
		"panicunsafeslicelen",
		"panicunsafeslicenilptr",
		"unsafestringcheckptr",
		"panicunsafestringlen",
		"panicunsafestringnilptr",
		"moveSlice",
		"moveSliceNoScan",
		"moveSliceNoCap",
		"moveSliceNoCapNoScan",
		"memmove",
		"memclrNoHeapPointers",
		"memclrHasPointers",
		"memequal",
		"memequal0",
		"memequal8",
		"memequal16",
		"memequal32",
		"memequal64",
		"memequal128",
		"f32equal",
		"f64equal",
		"c64equal",
		"c128equal",
		"strequal",
		"interequal",
		"nilinterequal",
		"memhash",
		"memhash0",
		"memhash8",
		"memhash16",
		"memhash32",
		"memhash64",
		"memhash128",
		"f32hash",
		"f64hash",
		"c64hash",
		"c128hash",
		"strhash",
		"interhash",
		"nilinterhash",
		"int64div",
		"uint64div",
		"int64mod",
		"uint64mod",
		"float64toint64",
		"float64touint64",
		"float64touint32",
		"int64tofloat64",
		"int64tofloat32",
		"uint64tofloat64",
		"uint64tofloat32",
		"uint32tofloat64",
		"complex128div",
		"racefuncenter",
		"racefuncexit",
		"raceread",
		"racewrite",
		"racereadrange",
		"racewriterange",
		"msanread",
		"msanwrite",
		"msanmove",
		"asanread",
		"asanwrite",
		"checkptrAlignment",
		"checkptrArithmetic",
		"libfuzzerTraceCmp1",
		"libfuzzerTraceCmp2",
		"libfuzzerTraceCmp4",
		"libfuzzerTraceCmp8",
		"libfuzzerTraceConstCmp1",
		"libfuzzerTraceConstCmp2",
		"libfuzzerTraceConstCmp4",
		"libfuzzerTraceConstCmp8",
		"libfuzzerHookStrCmp",
		"libfuzzerHookEqualFold",
		"addCovMeta",
		"x86HasAVX",
		"x86HasFMA",
		"x86HasPOPCNT",
		"x86HasSSE41",
		"armHasVFPv4",
		"arm64HasATOMICS",
		"loong64HasLAMCAS",
		"loong64HasLAM_BH",
		"loong64HasDBAR_HINTS",
		"loong64HasLSX",
		"riscv64HasZbb",
		"asanregisterglobals",
		"KeepAlive",
		"deferproc",
		"deferprocStack",
		"deferreturn",
		"newproc",
		"panicoverflow",
		"sigpanic",
		"gcWriteBarrier1",
		"gcWriteBarrier2",
		"gcWriteBarrier3",
		"gcWriteBarrier4",
		"gcWriteBarrier5",
		"gcWriteBarrier6",
		"gcWriteBarrier7",
		"gcWriteBarrier8",
		"duffzero",
		"duffcopy",
		"morestack",
		"morestackc",
		"morestack_noctxt",
		"retpolineAX",
		"retpolineCX",
		"retpolineDX",
		"retpolineBX",
		"retpolineBP",
		"retpolineSI",
		"retpolineDI",
		"retpolineR8",
		"retpolineR9",
		"retpolineR10",
		"retpolineR11",
		"retpolineR12",
		"retpolineR13",
		"retpolineR14",
		"retpolineR15",
		"tls_g",
		"printfloat",
		"printcomplex",
		"mapiterinit",
		"mapiternext",
		"mapinitnoop",
		"memequal_varlen",
		"memhash_varlen",
		"gcWriteBarrier",
		"gcWriteBarrierBP",
		"gcWriteBarrierBX",
		"gcWriteBarrierCX",
		"gcWriteBarrierDX",
		"gcWriteBarrierR8",
		"gcWriteBarrierR9",
		"gcWriteBarrierSI",
		"panicIndex",
		"panicIndexU",
		"panicSliceAlen",
		"panicSliceAlenU",
		"panicSliceAcap",
		"panicSliceAcapU",
		"panicSliceB",
		"panicSliceBU",
		"panicSlice3Alen",
		"panicSlice3AlenU",
		"panicSlice3Acap",
		"panicSlice3AcapU",
		"panicSlice3B",
		"panicSlice3BU",
		"panicSlice3C",
		"panicSlice3CU",
		"panicSliceConvert",
		"panicExtendIndex",
		"panicExtendIndexU",
		"panicExtendSliceAlen",
		"panicExtendSliceAlenU",
		"panicExtendSliceAcap",
		"panicExtendSliceAcapU",
		"panicExtendSliceB",
		"panicExtendSliceBU",
		"panicExtendSlice3Alen",
		"panicExtendSlice3AlenU",
		"panicExtendSlice3Acap",
		"panicExtendSlice3AcapU",
		"panicExtendSlice3B",
		"panicExtendSlice3BU",
		"panicExtendSlice3C",
		"panicExtendSlice3CU",
		"wbZero",
		"wbMove",
		"zeroVal",
		"unreachableMethod",
		"emptyInterfaceSwitchCache",
		"emptyTypeAssert",
		"emptyTypeAssertCache",
		"staticuint64s",
		"udiv",
		"zerobase",
		"bss",
		"ebss",
		"data",
		"edata",
		"gcbss",
		"egcbss",
		"gcdata",
		"egcdata",
		"noptrbss",
		"enoptrbss",
		"noptrdata",
		"enoptrdata",
		"rodata",
		"erodata",
		"text",
		"etext",
		"types",
		"etypes",
		"symtab",
		"esymtab",
		"pclntab",
		"epclntab",
		"functab",
		"funcnametab",
		"cutab",
		"filetab",
		"pctab",
		"pcheader",
		"findfunctab",
		"moduledata",
		"firstmoduledata",
		"lastmoduledatap",
		"modulehash",
		"textsectionmap",
		"typelink",
		"itablink",
		"buildVersion",
		"modinfo",
		"runtime_inittasks",
		"tlsg",
		"goarm",
		"goarmsoftfp",
		"isarchive",
		"islibrary",
		"covctrs",
		"ecovctrs",
		"cgoCheckMemmove",
		"cgoCheckPtrWrite",
		"deferprocat",
		"mallocgcTinySC2",
		"panicBounds",
		"panicExtend",
		"panicSimdImm",
		"wasmDiv",
		"wasmTruncS",
		"wasmTruncU",
		"fadd32",
		"fadd64",
		"fmul32",
		"fmul64",
		"fdiv32",
		"fdiv64",
		"feq64",
		"feq32",
		"fgt64",
		"fgt32",
		"fge64",
		"fge32",
		"fint32to32",
		"f32toint32",
		"fint64to32",
		"f32toint64",
		"fuint64to32",
		"f32touint64",
		"fint32to64",
		"f64toint32",
		"fint64to64",
		"f64toint64",
		"fuint64to64",
		"f64touint64",
		"f32to64",
		"f64to32",
	},
	"type:*unsafe": {
		"Pointer",
	},
	"type:unsafe": {
		"Pointer",
	},
}

var reflectSkipPkg = map[string]bool{
	"fmt": true,
}
`[1:]))

type tmplData struct {
	GoVersions          []string
	RuntimePkgPaths     []versionedString
	RuntimeAndLinknamed []versionedString
	CompilerIntrinsics  []tmplIntrinsic
}

type tmplIntrinsic struct {
	Path  string
	Names []versionedString
}

func (t tmplIntrinsic) Compare(t2 tmplIntrinsic) int {
	return cmp.Compare(t.Path, t2.Path)
}

func (t tmplIntrinsic) Equal(t2 tmplIntrinsic) bool {
	return t.Compare(t2) == 0
}

type versionedString struct {
	String        string
	GoVersionLang string
	Platform      goPlatform
}

func (v versionedString) Compare(v2 versionedString) int {
	if c := cmp.Compare(v.String, v2.String); c != 0 {
		return c
	}
	// Negated so that newer Go versions go first.
	if c := -cmp.Compare(v.GoVersionLang, v2.GoVersionLang); c != 0 {
		return c
	}
	// Platforms with a lower priority go first.
	return cmp.Compare(v.Platform.Priority, v2.Platform.Priority)
}

func (v versionedString) Equal(v2 versionedString) bool {
	// Note that we do equality based on String alone,
	// because we only need one String entry with the latest version.
	return v.String == v2.String
}

func cmdGo(goVersion string, platform goPlatform, args ...string) versionedString {
	cmd := exec.Command("go", args...)
	cmd.Env = append(cmd.Environ(), "GOTOOLCHAIN="+goVersion)
	if platform.GOOS != "" {
		cmd.Env = append(cmd.Env, "GOOS="+platform.GOOS, "GOARCH="+platform.GOARCH)
	}
	out, err := cmd.Output()
	if err != nil {
		panic(err)
	}
	return versionedString{
		String:        string(bytes.TrimSpace(out)), // no trailing newline
		GoVersionLang: version.Lang(goVersion),
		Platform:      platform,
	}
}

func readFile(path string) string {
	data, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	return string(data)
}

func lines(vs versionedString) []versionedString {
	split := strings.Split(vs.String, "\n")
	var versioned []versionedString
	for _, s := range split {
		versioned = append(versioned, versionedString{
			String:        s,
			GoVersionLang: vs.GoVersionLang,
			Platform:      vs.Platform,
		})
	}
	return versioned
}

var rxLinkname = regexp.MustCompile(`^//go:linkname .* ([^.]*)\.[^.]*$`)
var rxIntrinsic = regexp.MustCompile(`\b(add|addF|alias)\("([^"]*)", "([^"]*)",`)
var rxStringEntry = regexp.MustCompile(`^\s*"([^"]+)",$`)

func main() {
	var goroots []versionedString
	for _, goVersion := range goVersions {
		goroots = append(goroots, cmdGo(goVersion, goPlatform{}, "env", "GOROOT"))
	}

	var runtimePkgPaths []versionedString
	for _, goroot := range goroots {
		inRuntimePkgs := false
		for line := range strings.SplitSeq(readFile(filepath.Join(
			goroot.String, "src", "cmd", "internal", "objabi", "pkgspecial.go",
		)), "\n") {
			switch {
			case line == "var runtimePkgs = []string{":
				inRuntimePkgs = true
			case inRuntimePkgs && line == "}":
				inRuntimePkgs = false
			case inRuntimePkgs:
				if match := rxStringEntry.FindStringSubmatch(line); match != nil {
					runtimePkgPaths = append(runtimePkgPaths, versionedString{
						String:        match[1],
						GoVersionLang: goroot.GoVersionLang,
					})
				}
			}
		}
	}
	slices.SortFunc(runtimePkgPaths, versionedString.Compare)
	runtimePkgPaths = slices.CompactFunc(runtimePkgPaths, versionedString.Equal)

	// All packages that the runtime linknames to, except runtime and its dependencies.
	// This resulting list is what we need to "go list" when obfuscating the runtime,
	// as they are the packages that we may be missing.
	var runtimeAndLinknamed []versionedString
	for _, goroot := range goroots {
		runtimeGoFiles, err := filepath.Glob(filepath.Join(goroot.String, "src", "runtime", "*.go"))
		if err != nil {
			panic(err)
		}
		for _, goFile := range runtimeGoFiles {
			for line := range strings.SplitSeq(readFile(goFile), "\n") {
				m := rxLinkname.FindStringSubmatch(line)
				if m == nil {
					continue
				}
				path := m[1]
				switch path {
				case "main", "runtime/metrics_test":
					continue
				}
				runtimeAndLinknamed = append(runtimeAndLinknamed, versionedString{
					String:        path,
					GoVersionLang: goroot.GoVersionLang,
				})
			}
		}
	}
	slices.SortFunc(runtimeAndLinknamed, versionedString.Compare)
	runtimeAndLinknamed = slices.CompactFunc(runtimeAndLinknamed, versionedString.Equal)

	compilerIntrinsicsIndexByPath := make(map[string]int)
	var compilerIntrinsics []tmplIntrinsic
	for _, goroot := range goroots {
		for line := range strings.SplitSeq(readFile(filepath.Join(
			goroot.String, "src", "cmd", "compile", "internal", "ssagen", "intrinsics.go",
		)), "\n") {
			m := rxIntrinsic.FindStringSubmatch(line)
			if m == nil {
				continue
			}
			path, name := m[2], m[3]
			vs := versionedString{
				String:        name,
				GoVersionLang: goroot.GoVersionLang,
			}
			if i, ok := compilerIntrinsicsIndexByPath[path]; !ok {
				compilerIntrinsicsIndexByPath[path] = len(compilerIntrinsics)
				compilerIntrinsics = append(compilerIntrinsics, tmplIntrinsic{
					Path:  path,
					Names: []versionedString{vs},
				})
			} else {
				compilerIntrinsics[i].Names = append(compilerIntrinsics[i].Names, vs)
			}
		}
	}
	slices.SortFunc(compilerIntrinsics, tmplIntrinsic.Compare)
	compilerIntrinsics = slices.CompactFunc(compilerIntrinsics, tmplIntrinsic.Equal)
	for path := range compilerIntrinsics {
		intr := &compilerIntrinsics[path]
		slices.SortFunc(intr.Names, versionedString.Compare)
		intr.Names = slices.CompactFunc(intr.Names, versionedString.Equal)
	}

	var buf bytes.Buffer
	if err := tmplTables.Execute(&buf, tmplData{
		GoVersions:          goVersions,
		RuntimePkgPaths:     runtimePkgPaths,
		RuntimeAndLinknamed: runtimeAndLinknamed,
		CompilerIntrinsics:  compilerIntrinsics,
	}); err != nil {
		panic(err)
	}
	out := buf.Bytes()
	formatted, err := format.Source(out)
	if err != nil {
		fmt.Println(string(out))
		panic(err)
	}

	if err := os.WriteFile("go_std_tables.go", formatted, 0o666); err != nil {
		panic(err)
	}
}
